select prirad_startovni_cisla(1);
select prirad_startovni_cisla(2);
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 780, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 1 AND zavod_id = 1;
update tymy set cas_prvniho_kola = 755, cas_druheho_kola = 733, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 2 AND zavod_id = 1;
update tymy set cas_prvniho_kola = 752, cas_druheho_kola = 780, penalizace_prvni_kolo = 1 WHERE startovni_cislo = 3 AND zavod_id = 1;
update tymy set cas_prvniho_kola = 720, cas_druheho_kola = 783, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 1 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 759, cas_druheho_kola = 780, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 2 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 731, cas_druheho_kola = 761, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 3 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 733, cas_druheho_kola = 780, penalizace_prvni_kolo = 1 WHERE startovni_cislo = 4 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 780, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 5 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 752, cas_druheho_kola = 792, penalizace_prvni_kolo = 1 WHERE startovni_cislo = 6 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 780, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 7 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 782, penalizace_prvni_kolo = 0 WHERE startovni_cislo = 8 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 780, penalizace_prvni_kolo = 0 WHERE startovni_cislo = 9 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 731, cas_druheho_kola = 789, penalizace_prvni_kolo = 2 WHERE startovni_cislo = 10 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 750, cas_druheho_kola = 760, penalizace_prvni_kolo = 0 WHERE startovni_cislo = 11 AND zavod_id = 2;
update tymy set cas_prvniho_kola = 744, cas_druheho_kola = 711, penalizace_prvni_kolo = 6 WHERE startovni_cislo = 12 AND zavod_id = 2;
