/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBTools;
import DB.Kategorie;
import DB.Kun;
import DB.Osoba;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lada
 */
public class PanelRegistraceTymu extends javax.swing.JFrame {
    private ButtonColumn buttonColumnKone;
    private ButtonColumn buttonColumnPrisedici;

    /**
     * Creates new form PanelRegistraceTymu
     */
    public PanelRegistraceTymu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//BLOKOVANE-GEN-BEGIN:initComponents
    private void initComponents() {

        JmenoTymuField = new javax.swing.JTextField();
        JmenoTymuPopisek = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kategorieCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        prisediciTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        koneTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jezdecTable = new javax.swing.JTable();
        ulozitButton = new javax.swing.JButton();
        stornoButton = new javax.swing.JButton();

        JmenoTymuField.setText("jTextField1");
        JmenoTymuField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamenoTymuFieldActionPerformed(evt);
            }
        });

        JmenoTymuPopisek.setText("Jméno týmu:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vytvoření nového týmu");

        jLabel2.setText("Kategorie");
        TypedQuery queryS = DBTools.getInstance().getEm().createQuery("Select s from Kategorie s", Kategorie.class);
        List<Kategorie> listKategorie = queryS.getResultList();
        String[] model = new String[listKategorie.size()];
        for (int i = 0; i < listKategorie.size(); i++) {
            model[i] = listKategorie.get(i).getNazev();
        }

        kategorieCombo.setModel(new javax.swing.DefaultComboBoxModel(model));
        kategorieCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategorieComboActionPerformed(evt);
            }
        });
        //System.out.println(kategorieCombo.getSelectedItem());

        jLabel3.setText("Jezdec");

        jLabel4.setText("Přísedící");

        jLabel6.setText("Koně");
        
        zmenit = new AbstractAction() {
            private int typ;
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                if(table.equals(koneTable)){
                    typ = UniverzalniVybiratko.TYP_KUN;
                }else{
                    typ = UniverzalniVybiratko.TYP_OSOBA;
                }
                UniverzalniVybiratko uv = new UniverzalniVybiratko(PanelRegistraceTymu.this, true, typ);
                Long result = uv.showDialog();
                if(result==null){
                    return;
                }else{
                    PanelRegistraceTymu.this.setRow(table, modelRow, typ, result);
                }
                
                //((DefaultTableModel) table.getModel()).removeRow(modelRow);
            }

            
        };

        prisediciTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Jmeno", "Prijmeni", "Datum narozeni", ""
                }
        ));
        //prisediciTable.setEnabled(false);
        jScrollPane2.setViewportView(prisediciTable);

        

        koneTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Jmeno", "Plemeno", "Majitel", ""
                }
        ));
        ButtonColumn buttonColumnKone = new ButtonColumn(koneTable, zmenit, 3);
        jScrollPane3.setViewportView(koneTable);
        
        updateTables(kategorieCombo.getSelectedItem().toString());
        

        jezdecTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"---", "---", "---", "---", "zmenit"},},
                new String[]{
                    "id", "Jmeno", "Prijmeni", "Datum narozeni", ""
                }
        ));
        TableColumnModel cm = jezdecTable.getColumnModel();
        TableColumn id_column = cm.getColumn(0);
        cm.removeColumn(id_column);

        ButtonColumn buttonColumnJezdec = new ButtonColumn(jezdecTable, zmenit, 3);
        jScrollPane4.setViewportView(jezdecTable);

        ulozitButton.setText("Ulozit");

        stornoButton.setText("Storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(jScrollPane4))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(139, 139, 139)
                                                                                        .addComponent(jLabel1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(7, 7, 7)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(JmenoTymuPopisek, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                        .addComponent(JmenoTymuField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addGap(33, 33, 33)
                                                                                                        .addComponent(kategorieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                        .addGap(187, 187, 187)))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jScrollPane2)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel6))
                                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stornoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ulozitButton)
                        .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JmenoTymuPopisek)
                                .addComponent(JmenoTymuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kategorieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ulozitButton)
                                .addComponent(stornoButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>                        
    
    private void updateTables(String nazevKategorie){
        String sql = "select * from kategorie where nazev=?";
        Query query = DBTools.getInstance().getEm().createNativeQuery(sql, Kategorie.class);

        query.setParameter(1, nazevKategorie);

        Kategorie aktKat = (Kategorie) query.getSingleResult();

        //System.out.println(aktKat);

        String[][] koneData = new String[aktKat.getPocet_koni()][5];
        for(String[] a: koneData){
            a[0] = "---";
            a[1] = "---";
            a[2] = "---";
            a[3] = "---";
            a[4] = "zmenit";
        }

        koneTable.setModel(new javax.swing.table.DefaultTableModel(
                koneData,
                new String[]{
                    "id","Jmeno", "Plemeno", "Majitel", ""
                }
        ));
        
        
        String[][] prisediciData = new String[aktKat.getPocet_prisedicich()][5];
        for(String[] a: prisediciData){
            a[0] = "---";
            a[1] = "---";
            a[2] = "---";
            a[3] = "---";
            a[4] = "zmenit";
        }

        prisediciTable.setModel(new javax.swing.table.DefaultTableModel(
                prisediciData,
                new String[]{
                    "id", "Jmeno", "Prijmeni", "Datum narozeni", ""
                }
        ));
        
        
        TableColumnModel cm = prisediciTable.getColumnModel();
        TableColumn id_column = cm.getColumn(0);
        cm.removeColumn(id_column);
        
        cm = koneTable.getColumnModel();
        id_column = cm.getColumn(0);
        cm.removeColumn(id_column);
        
        buttonColumnKone = new ButtonColumn(koneTable, zmenit, 3);
        buttonColumnPrisedici = new ButtonColumn(prisediciTable, zmenit, 3);
    }
    
    private void setRow(JTable table, int modelRow, int typ, Long result) {
        System.out.println("typ: "+typ+";  result: "+result);
        if(typ == UniverzalniVybiratko.TYP_OSOBA){
            Osoba os = DBTools.getInstance().getEm().find(Osoba.class, result);
            TableModel mod = table.getModel();
            mod.setValueAt(os.getOsoba_id(), modelRow, 0);
            mod.setValueAt(os.getJmeno(), modelRow, 1);
            mod.setValueAt(os.getPrijmeni(), modelRow, 2);
            mod.setValueAt(os.getDatum_narozeni(), modelRow, 3);
        }else{
            Kun kun = DBTools.getInstance().getEm().find(Kun.class, result);
            TableModel mod = table.getModel();
            mod.setValueAt(kun.getKun_id(), modelRow, 0);
            mod.setValueAt(kun.getJmeno(), modelRow, 1);
            mod.setValueAt(kun.getPlemeno(), modelRow, 2);
            mod.setValueAt(kun.getMajitel(), modelRow, 3);
            
        }
    }

    private void JamenoTymuFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamenoTymuFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamenoTymuFieldActionPerformed

    private void kategorieComboActionPerformed(java.awt.event.ActionEvent evt) {
        //System.out.println(evt.getActionCommand());
        updateTables( ((JComboBox)evt.getSource()).getSelectedItem().toString() );
        //updateTables(evt.getActionCommand());
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String[] args) {
        PanelRegistraceTymu fr = new PanelRegistraceTymu();
        fr.setVisible(true);
    }

    // Variables declaration - do not modify//BLOKOVANE-GEN-BEGIN:variables
    private javax.swing.JTextField JmenoTymuField;
    private javax.swing.JLabel JmenoTymuPopisek;
    private javax.swing.JButton ulozitButton;
    private javax.swing.JButton stornoButton;
    private javax.swing.JComboBox kategorieCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable prisediciTable;
    private javax.swing.JTable koneTable;
    private javax.swing.JTable jezdecTable;
    private Action zmenit;
    // End of variables declaration                   

}
