/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DBTools;
import DB.Kun;
import DB.Osoba;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.persistence.TypedQuery;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jonas
 */
public class RegistraceOsobFrame extends javax.swing.JFrame {

    public static void main(String[] args) {
        new RegistraceOsobFrame().setVisible(true);
    }

    /**
     * Creates new form NewJFrame
     */
    public RegistraceOsobFrame() {
        super("Registrace členů");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//BLOKOVANE-BLOKOVANE-GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        hledejButton = new javax.swing.JButton();
        hledejField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        osobyTable = new javax.swing.JTable();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        nextButton.setText("další stránka");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        prevButton.setText("předchozí stránka");

        newButton.setText("Nový člen");

        hledejButton.setText("hledej");

        //hledejField.setText("jTextField1");
        jLabel1.setText(""); //Registrace členu");
        TypedQuery queryS = DBTools.getInstance().getEm().createQuery("Select s from Osoba s", Osoba.class);
        List<Osoba> listOsoby = queryS.getResultList();
         Object[][] data = new Object [listOsoby.size()][6];
        for (int i = 0; i < listOsoby.size(); i++) {
            data[i][0]=listOsoby.get(i).getOsoba_id();
            data[i][1]=listOsoby.get(i).getJmeno();
            data[i][2]=listOsoby.get(i).getPrijmeni();
            data[i][3]=listOsoby.get(i).getDatum_narozeni();
            data[i][4]="Upravit";
            data[i][5]="Smazat";
        }
        osobyTable.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "hidden Id", "Jméno", "Příjmení", "Datum narození", "upravit", "smazat"
                }
        ));
        TableColumnModel cm = osobyTable.getColumnModel();
        TableColumn id_column = cm.getColumn(0);
        cm.removeColumn(id_column);
        jScrollPane2.setViewportView(osobyTable);
        final JFrame frame = this;

        Action delete = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                Long id = (Long) ((DefaultTableModel) table.getModel()).getValueAt(modelRow, 0);
                
                Object[] options = {"Smazat", "Storno"};
                int n = JOptionPane.showOptionDialog(frame,
                        "Smazání osoby je nevratné!\n Opravdu si přejete pokračovat?",
                        "Potvrzení smazání",
                       
                        JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[1]);
                if(n==0){
                    ((DefaultTableModel) table.getModel()).removeRow(modelRow);
                    System.out.println("deleting id: " + id);
                }
                /*final JOptionPane optionPane = new JOptionPane(
                        "Smazání osoby je nevratné!",
                        JOptionPane.QUESTION_MESSAGE,
                        JOptionPane.YES_NO_OPTION);*/
            }
        };

        Action edit = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int modelRow = Integer.valueOf(e.getActionCommand());
                Long id = (Long) ((DefaultTableModel) table.getModel()).getValueAt(modelRow, 0);
                //TODO: 
                System.out.println("editing id: " + id);
                EditOsobaFrame editOsoba = new EditOsobaFrame(id);
                editOsoba.setVisible(true);
            }
        };

        ButtonColumn buttonColumnDelete = new ButtonColumn(osobyTable, delete, 4);
        ButtonColumn buttonColumnEdit = new ButtonColumn(osobyTable, edit, 3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(213, 213, 213)
                                        .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addComponent(prevButton)
                                                        .addGap(49, 49, 49)
                                                        .addComponent(nextButton))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(hledejField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(hledejButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hledejField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hledejButton)
                                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(prevButton)
                                .addComponent(nextButton))
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistraceOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistraceOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistraceOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistraceOsobFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistraceOsobFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//BLOKOVANE-BLOKOVANE-GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton hledejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable osobyTable;
    private javax.swing.JTextField hledejField;
    // End of variables declaration                   
}
