/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Lada
 */
public class VstupniFormular extends javax.swing.JFrame {

    public static void main(String[] args) {
        VstupniFormular vf = new VstupniFormular();
        vf.setVisible(true);
    }
    
    /**
     * Creates new form VstupniFormular
     */
    public VstupniFormular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//BLOKOVANE-GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regOsobButton = new javax.swing.JButton();
        regZavodyButton = new javax.swing.JButton();
        vysledkyButton = new javax.swing.JButton();
        regKoniButton = new javax.swing.JButton();
        regStajiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Databáze závodů ČJF");

        regOsobButton.setText("Ragistrace členů do ČJF");
        regOsobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regOsobButtonActionPerformed(evt);
            }
        });

        regZavodyButton.setText("Registrace k závodům");
        regZavodyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regZavodyButtonActionPerformed(evt);
            }
        });

        vysledkyButton.setText("Statistiky/Výsledkové listiny");
        vysledkyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vysledkyButtonActionPerformed(evt);
            }
        });

        regKoniButton.setText("Ragistrace koní do ČJF");
        regKoniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regKoniButtonActionPerformed(evt);
            }
        });

        regStajiButton.setText("Registrace stájí");
        regStajiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStajiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vysledkyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regZavodyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regOsobButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regKoniButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regStajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(regOsobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regKoniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regStajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regZavodyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vysledkyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vysledkyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vysledkyButtonActionPerformed
        
    }//GEN-LAST:event_vysledkyButtonActionPerformed

    private void regKoniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regKoniButtonActionPerformed
        RegistraceKonuFrame fr = new RegistraceKonuFrame();
        fr.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_regKoniButtonActionPerformed

    private void regOsobButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        RegistraceOsobFrame fr = new RegistraceOsobFrame();
        fr.setVisible(true);// TODO add your handling code here:
    }
    
    private void regZavodyButtonActionPerformed(java.awt.event.ActionEvent evt) {       
        RegistraceZavodFrame fr = new RegistraceZavodFrame();
        fr.setVisible(true);// TODO add your handling code here:
    }
    
    private void regStajiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStajiButtonActionPerformed
        RegistraceStajiFrame fr = new RegistraceStajiFrame();
        fr.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_regStajiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VstupniFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VstupniFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VstupniFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VstupniFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VstupniFormular().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//BLOKOVANE-GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regKoniButton;
    private javax.swing.JButton regOsobButton;
    private javax.swing.JButton regStajiButton;
    private javax.swing.JButton regZavodyButton;
    private javax.swing.JButton vysledkyButton;
    // End of variables declaration//GEN-END:variables
}
